/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as DeptAdminRouteImport } from './routes/dept-admin'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QrPassRouteImport } from './routes/qr-pass'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as VotingRouteImport } from './routes/voting'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminContestantsRouteImport } from './routes/admin.contestants'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminJudgesRouteImport } from './routes/admin.judges'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSpecialGuestsRouteImport } from './routes/admin.special-guests'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSubEventsRouteImport } from './routes/admin.sub-events'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVotingRouteImport } from './routes/admin.voting'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AuthDepartmentAdminRouteImport } from './routes/auth.department-admin'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as CertificatesVerifyRouteImport } from './routes/certificates.verify'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator.index'
import { Route as CoordinatorContestantsRouteImport } from './routes/coordinator.contestants'
import { Route as CoordinatorEventsRouteImport } from './routes/coordinator.events'
import { Route as CoordinatorJudgesRouteImport } from './routes/coordinator.judges'
import { Route as CoordinatorSubEventsRouteImport } from './routes/coordinator.sub-events'
import { Route as CoordinatorVotingRouteImport } from './routes/coordinator.voting'
import { Route as DeptAdminIndexRouteImport } from './routes/dept-admin.index'
import { Route as DeptAdminAttendanceRouteImport } from './routes/dept-admin.attendance'
import { Route as DeptAdminCertificatesRouteImport } from './routes/dept-admin.certificates'
import { Route as DeptAdminEventsRouteImport } from './routes/dept-admin.events'
import { Route as DeptAdminFacultyRouteImport } from './routes/dept-admin.faculty'
import { Route as DeptAdminGalleryRouteImport } from './routes/dept-admin.gallery'
import { Route as DeptAdminRegistrationsRouteImport } from './routes/dept-admin.registrations'
import { Route as DeptAdminReportsRouteImport } from './routes/dept-admin.reports'
import { Route as DeptAdminSettingsRouteImport } from './routes/dept-admin.settings'
import { Route as DeptAdminStudentsRouteImport } from './routes/dept-admin.students'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveStreamIdRouteImport } from './routes/live.$streamId'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffAttendanceRouteImport } from './routes/staff.attendance'
import { Route as StaffRegistrationsRouteImport } from './routes/staff.registrations'
import { Route as StaffScanRouteImport } from './routes/staff.scan'
import { Route as EventsEventIdRegisterRouteImport } from './routes/events.$eventId.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminRoute = DeptAdminRouteImport.update({
  id: '/dept-admin',
  path: '/dept-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QrPassRoute = QrPassRouteImport.update({
  id: '/qr-pass',
  path: '/qr-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const VotingRoute = VotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestantsRoute = AdminContestantsRouteImport.update({
  id: '/contestants',
  path: '/contestants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJudgesRoute = AdminJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpecialGuestsRoute = AdminSpecialGuestsRouteImport.update({
  id: '/special-guests',
  path: '/special-guests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubEventsRoute = AdminSubEventsRouteImport.update({
  id: '/sub-events',
  path: '/sub-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVotingRoute = AdminVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => AdminRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDepartmentAdminRoute = AuthDepartmentAdminRouteImport.update({
  id: '/auth/department-admin',
  path: '/auth/department-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesVerifyRoute = CertificatesVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => CertificatesRoute,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorContestantsRoute = CoordinatorContestantsRouteImport.update({
  id: '/contestants',
  path: '/contestants',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorEventsRoute = CoordinatorEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorJudgesRoute = CoordinatorJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorSubEventsRoute = CoordinatorSubEventsRouteImport.update({
  id: '/sub-events',
  path: '/sub-events',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorVotingRoute = CoordinatorVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => CoordinatorRoute,
} as any)
const DeptAdminIndexRoute = DeptAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminAttendanceRoute = DeptAdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminCertificatesRoute = DeptAdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminEventsRoute = DeptAdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminFacultyRoute = DeptAdminFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminGalleryRoute = DeptAdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminRegistrationsRoute = DeptAdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminReportsRoute = DeptAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminSettingsRoute = DeptAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeptAdminRoute,
} as any)
const DeptAdminStudentsRoute = DeptAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DeptAdminRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStreamIdRoute = LiveStreamIdRouteImport.update({
  id: '/live/$streamId',
  path: '/live/$streamId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRegistrationsRoute = StaffRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffScanRoute = StaffScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => StaffRoute,
} as any)
const EventsEventIdRegisterRoute = EventsEventIdRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alumni': typeof AlumniRoute
  '/calendar': typeof CalendarRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/dept-admin': typeof DeptAdminRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/qr-pass': typeof QrPassRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/voting': typeof VotingRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-guests': typeof AdminSpecialGuestsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/sub-events': typeof AdminSubEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voting': typeof AdminVotingRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/department-admin': typeof AuthDepartmentAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/coordinator/contestants': typeof CoordinatorContestantsRoute
  '/coordinator/events': typeof CoordinatorEventsRoute
  '/coordinator/judges': typeof CoordinatorJudgesRoute
  '/coordinator/sub-events': typeof CoordinatorSubEventsRoute
  '/coordinator/voting': typeof CoordinatorVotingRoute
  '/dept-admin/attendance': typeof DeptAdminAttendanceRoute
  '/dept-admin/certificates': typeof DeptAdminCertificatesRoute
  '/dept-admin/events': typeof DeptAdminEventsRoute
  '/dept-admin/faculty': typeof DeptAdminFacultyRoute
  '/dept-admin/gallery': typeof DeptAdminGalleryRoute
  '/dept-admin/registrations': typeof DeptAdminRegistrationsRoute
  '/dept-admin/reports': typeof DeptAdminReportsRoute
  '/dept-admin/settings': typeof DeptAdminSettingsRoute
  '/dept-admin/students': typeof DeptAdminStudentsRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/live/$streamId': typeof LiveStreamIdRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/registrations': typeof StaffRegistrationsRoute
  '/staff/scan': typeof StaffScanRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/dept-admin/': typeof DeptAdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/live/': typeof LiveIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/events/$eventId/register': typeof EventsEventIdRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/calendar': typeof CalendarRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/qr-pass': typeof QrPassRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/voting': typeof VotingRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-guests': typeof AdminSpecialGuestsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/sub-events': typeof AdminSubEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voting': typeof AdminVotingRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/department-admin': typeof AuthDepartmentAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/coordinator/contestants': typeof CoordinatorContestantsRoute
  '/coordinator/events': typeof CoordinatorEventsRoute
  '/coordinator/judges': typeof CoordinatorJudgesRoute
  '/coordinator/sub-events': typeof CoordinatorSubEventsRoute
  '/coordinator/voting': typeof CoordinatorVotingRoute
  '/dept-admin/attendance': typeof DeptAdminAttendanceRoute
  '/dept-admin/certificates': typeof DeptAdminCertificatesRoute
  '/dept-admin/events': typeof DeptAdminEventsRoute
  '/dept-admin/faculty': typeof DeptAdminFacultyRoute
  '/dept-admin/gallery': typeof DeptAdminGalleryRoute
  '/dept-admin/registrations': typeof DeptAdminRegistrationsRoute
  '/dept-admin/reports': typeof DeptAdminReportsRoute
  '/dept-admin/settings': typeof DeptAdminSettingsRoute
  '/dept-admin/students': typeof DeptAdminStudentsRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/live/$streamId': typeof LiveStreamIdRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/registrations': typeof StaffRegistrationsRoute
  '/staff/scan': typeof StaffScanRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/dept-admin': typeof DeptAdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/live': typeof LiveIndexRoute
  '/staff': typeof StaffIndexRoute
  '/events/$eventId/register': typeof EventsEventIdRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alumni': typeof AlumniRoute
  '/calendar': typeof CalendarRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/dept-admin': typeof DeptAdminRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/qr-pass': typeof QrPassRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/voting': typeof VotingRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/contestants': typeof AdminContestantsRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-guests': typeof AdminSpecialGuestsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/sub-events': typeof AdminSubEventsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voting': typeof AdminVotingRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/department-admin': typeof AuthDepartmentAdminRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/certificates/verify': typeof CertificatesVerifyRoute
  '/coordinator/contestants': typeof CoordinatorContestantsRoute
  '/coordinator/events': typeof CoordinatorEventsRoute
  '/coordinator/judges': typeof CoordinatorJudgesRoute
  '/coordinator/sub-events': typeof CoordinatorSubEventsRoute
  '/coordinator/voting': typeof CoordinatorVotingRoute
  '/dept-admin/attendance': typeof DeptAdminAttendanceRoute
  '/dept-admin/certificates': typeof DeptAdminCertificatesRoute
  '/dept-admin/events': typeof DeptAdminEventsRoute
  '/dept-admin/faculty': typeof DeptAdminFacultyRoute
  '/dept-admin/gallery': typeof DeptAdminGalleryRoute
  '/dept-admin/registrations': typeof DeptAdminRegistrationsRoute
  '/dept-admin/reports': typeof DeptAdminReportsRoute
  '/dept-admin/settings': typeof DeptAdminSettingsRoute
  '/dept-admin/students': typeof DeptAdminStudentsRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/live/$streamId': typeof LiveStreamIdRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/registrations': typeof StaffRegistrationsRoute
  '/staff/scan': typeof StaffScanRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/dept-admin/': typeof DeptAdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/live/': typeof LiveIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/events/$eventId/register': typeof EventsEventIdRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alumni'
    | '/calendar'
    | '/certificates'
    | '/coordinator'
    | '/dept-admin'
    | '/gallery'
    | '/help'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/qr-pass'
    | '/settings'
    | '/sitemap.xml'
    | '/staff'
    | '/voting'
    | '/admin/attendance'
    | '/admin/certificates'
    | '/admin/contestants'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/judges'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/special-guests'
    | '/admin/sponsors'
    | '/admin/staff'
    | '/admin/sub-events'
    | '/admin/users'
    | '/admin/voting'
    | '/auth/admin'
    | '/auth/department-admin'
    | '/auth/login'
    | '/auth/register'
    | '/certificates/verify'
    | '/coordinator/contestants'
    | '/coordinator/events'
    | '/coordinator/judges'
    | '/coordinator/sub-events'
    | '/coordinator/voting'
    | '/dept-admin/attendance'
    | '/dept-admin/certificates'
    | '/dept-admin/events'
    | '/dept-admin/faculty'
    | '/dept-admin/gallery'
    | '/dept-admin/registrations'
    | '/dept-admin/reports'
    | '/dept-admin/settings'
    | '/dept-admin/students'
    | '/events/$eventId'
    | '/live/$streamId'
    | '/staff/attendance'
    | '/staff/registrations'
    | '/staff/scan'
    | '/admin/'
    | '/auth/'
    | '/coordinator/'
    | '/dept-admin/'
    | '/events/'
    | '/live/'
    | '/staff/'
    | '/events/$eventId/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumni'
    | '/calendar'
    | '/certificates'
    | '/gallery'
    | '/help'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/qr-pass'
    | '/settings'
    | '/sitemap.xml'
    | '/voting'
    | '/admin/attendance'
    | '/admin/certificates'
    | '/admin/contestants'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/judges'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/special-guests'
    | '/admin/sponsors'
    | '/admin/staff'
    | '/admin/sub-events'
    | '/admin/users'
    | '/admin/voting'
    | '/auth/admin'
    | '/auth/department-admin'
    | '/auth/login'
    | '/auth/register'
    | '/certificates/verify'
    | '/coordinator/contestants'
    | '/coordinator/events'
    | '/coordinator/judges'
    | '/coordinator/sub-events'
    | '/coordinator/voting'
    | '/dept-admin/attendance'
    | '/dept-admin/certificates'
    | '/dept-admin/events'
    | '/dept-admin/faculty'
    | '/dept-admin/gallery'
    | '/dept-admin/registrations'
    | '/dept-admin/reports'
    | '/dept-admin/settings'
    | '/dept-admin/students'
    | '/events/$eventId'
    | '/live/$streamId'
    | '/staff/attendance'
    | '/staff/registrations'
    | '/staff/scan'
    | '/admin'
    | '/auth'
    | '/coordinator'
    | '/dept-admin'
    | '/events'
    | '/live'
    | '/staff'
    | '/events/$eventId/register'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alumni'
    | '/calendar'
    | '/certificates'
    | '/coordinator'
    | '/dept-admin'
    | '/gallery'
    | '/help'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/qr-pass'
    | '/settings'
    | '/sitemap.xml'
    | '/staff'
    | '/voting'
    | '/admin/attendance'
    | '/admin/certificates'
    | '/admin/contestants'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/judges'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/special-guests'
    | '/admin/sponsors'
    | '/admin/staff'
    | '/admin/sub-events'
    | '/admin/users'
    | '/admin/voting'
    | '/auth/admin'
    | '/auth/department-admin'
    | '/auth/login'
    | '/auth/register'
    | '/certificates/verify'
    | '/coordinator/contestants'
    | '/coordinator/events'
    | '/coordinator/judges'
    | '/coordinator/sub-events'
    | '/coordinator/voting'
    | '/dept-admin/attendance'
    | '/dept-admin/certificates'
    | '/dept-admin/events'
    | '/dept-admin/faculty'
    | '/dept-admin/gallery'
    | '/dept-admin/registrations'
    | '/dept-admin/reports'
    | '/dept-admin/settings'
    | '/dept-admin/students'
    | '/events/$eventId'
    | '/live/$streamId'
    | '/staff/attendance'
    | '/staff/registrations'
    | '/staff/scan'
    | '/admin/'
    | '/auth/'
    | '/coordinator/'
    | '/dept-admin/'
    | '/events/'
    | '/live/'
    | '/staff/'
    | '/events/$eventId/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlumniRoute: typeof AlumniRoute
  CalendarRoute: typeof CalendarRoute
  CertificatesRoute: typeof CertificatesRouteWithChildren
  CoordinatorRoute: typeof CoordinatorRouteWithChildren
  DeptAdminRoute: typeof DeptAdminRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  HelpRoute: typeof HelpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  QrPassRoute: typeof QrPassRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRouteWithChildren
  VotingRoute: typeof VotingRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthDepartmentAdminRoute: typeof AuthDepartmentAdminRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  LiveStreamIdRoute: typeof LiveStreamIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin': {
      id: '/dept-admin'
      path: '/dept-admin'
      fullPath: '/dept-admin'
      preLoaderRoute: typeof DeptAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-pass': {
      id: '/qr-pass'
      path: '/qr-pass'
      fullPath: '/qr-pass'
      preLoaderRoute: typeof QrPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voting': {
      id: '/voting'
      path: '/voting'
      fullPath: '/voting'
      preLoaderRoute: typeof VotingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contestants': {
      id: '/admin/contestants'
      path: '/contestants'
      fullPath: '/admin/contestants'
      preLoaderRoute: typeof AdminContestantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/judges': {
      id: '/admin/judges'
      path: '/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof AdminJudgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/special-guests': {
      id: '/admin/special-guests'
      path: '/special-guests'
      fullPath: '/admin/special-guests'
      preLoaderRoute: typeof AdminSpecialGuestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sub-events': {
      id: '/admin/sub-events'
      path: '/sub-events'
      fullPath: '/admin/sub-events'
      preLoaderRoute: typeof AdminSubEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voting': {
      id: '/admin/voting'
      path: '/voting'
      fullPath: '/admin/voting'
      preLoaderRoute: typeof AdminVotingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/department-admin': {
      id: '/auth/department-admin'
      path: '/auth/department-admin'
      fullPath: '/auth/department-admin'
      preLoaderRoute: typeof AuthDepartmentAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/verify': {
      id: '/certificates/verify'
      path: '/verify'
      fullPath: '/certificates/verify'
      preLoaderRoute: typeof CertificatesVerifyRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/contestants': {
      id: '/coordinator/contestants'
      path: '/contestants'
      fullPath: '/coordinator/contestants'
      preLoaderRoute: typeof CoordinatorContestantsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/events': {
      id: '/coordinator/events'
      path: '/events'
      fullPath: '/coordinator/events'
      preLoaderRoute: typeof CoordinatorEventsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/judges': {
      id: '/coordinator/judges'
      path: '/judges'
      fullPath: '/coordinator/judges'
      preLoaderRoute: typeof CoordinatorJudgesRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/sub-events': {
      id: '/coordinator/sub-events'
      path: '/sub-events'
      fullPath: '/coordinator/sub-events'
      preLoaderRoute: typeof CoordinatorSubEventsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/voting': {
      id: '/coordinator/voting'
      path: '/voting'
      fullPath: '/coordinator/voting'
      preLoaderRoute: typeof CoordinatorVotingRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/dept-admin/': {
      id: '/dept-admin/'
      path: '/'
      fullPath: '/dept-admin/'
      preLoaderRoute: typeof DeptAdminIndexRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/attendance': {
      id: '/dept-admin/attendance'
      path: '/attendance'
      fullPath: '/dept-admin/attendance'
      preLoaderRoute: typeof DeptAdminAttendanceRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/certificates': {
      id: '/dept-admin/certificates'
      path: '/certificates'
      fullPath: '/dept-admin/certificates'
      preLoaderRoute: typeof DeptAdminCertificatesRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/events': {
      id: '/dept-admin/events'
      path: '/events'
      fullPath: '/dept-admin/events'
      preLoaderRoute: typeof DeptAdminEventsRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/faculty': {
      id: '/dept-admin/faculty'
      path: '/faculty'
      fullPath: '/dept-admin/faculty'
      preLoaderRoute: typeof DeptAdminFacultyRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/gallery': {
      id: '/dept-admin/gallery'
      path: '/gallery'
      fullPath: '/dept-admin/gallery'
      preLoaderRoute: typeof DeptAdminGalleryRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/registrations': {
      id: '/dept-admin/registrations'
      path: '/registrations'
      fullPath: '/dept-admin/registrations'
      preLoaderRoute: typeof DeptAdminRegistrationsRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/reports': {
      id: '/dept-admin/reports'
      path: '/reports'
      fullPath: '/dept-admin/reports'
      preLoaderRoute: typeof DeptAdminReportsRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/settings': {
      id: '/dept-admin/settings'
      path: '/settings'
      fullPath: '/dept-admin/settings'
      preLoaderRoute: typeof DeptAdminSettingsRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/dept-admin/students': {
      id: '/dept-admin/students'
      path: '/students'
      fullPath: '/dept-admin/students'
      preLoaderRoute: typeof DeptAdminStudentsRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$streamId': {
      id: '/live/$streamId'
      path: '/live/$streamId'
      fullPath: '/live/$streamId'
      preLoaderRoute: typeof LiveStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/registrations': {
      id: '/staff/registrations'
      path: '/registrations'
      fullPath: '/staff/registrations'
      preLoaderRoute: typeof StaffRegistrationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/scan': {
      id: '/staff/scan'
      path: '/scan'
      fullPath: '/staff/scan'
      preLoaderRoute: typeof StaffScanRouteImport
      parentRoute: typeof StaffRoute
    }
    '/events/$eventId/register': {
      id: '/events/$eventId/register'
      path: '/register'
      fullPath: '/events/$eventId/register'
      preLoaderRoute: typeof EventsEventIdRegisterRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminContestantsRoute: typeof AdminContestantsRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminJudgesRoute: typeof AdminJudgesRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpecialGuestsRoute: typeof AdminSpecialGuestsRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubEventsRoute: typeof AdminSubEventsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVotingRoute: typeof AdminVotingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminContestantsRoute: AdminContestantsRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminJudgesRoute: AdminJudgesRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpecialGuestsRoute: AdminSpecialGuestsRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubEventsRoute: AdminSubEventsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVotingRoute: AdminVotingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CertificatesRouteChildren {
  CertificatesVerifyRoute: typeof CertificatesVerifyRoute
}

const CertificatesRouteChildren: CertificatesRouteChildren = {
  CertificatesVerifyRoute: CertificatesVerifyRoute,
}

const CertificatesRouteWithChildren = CertificatesRoute._addFileChildren(
  CertificatesRouteChildren,
)

interface CoordinatorRouteChildren {
  CoordinatorContestantsRoute: typeof CoordinatorContestantsRoute
  CoordinatorEventsRoute: typeof CoordinatorEventsRoute
  CoordinatorJudgesRoute: typeof CoordinatorJudgesRoute
  CoordinatorSubEventsRoute: typeof CoordinatorSubEventsRoute
  CoordinatorVotingRoute: typeof CoordinatorVotingRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
}

const CoordinatorRouteChildren: CoordinatorRouteChildren = {
  CoordinatorContestantsRoute: CoordinatorContestantsRoute,
  CoordinatorEventsRoute: CoordinatorEventsRoute,
  CoordinatorJudgesRoute: CoordinatorJudgesRoute,
  CoordinatorSubEventsRoute: CoordinatorSubEventsRoute,
  CoordinatorVotingRoute: CoordinatorVotingRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
}

const CoordinatorRouteWithChildren = CoordinatorRoute._addFileChildren(
  CoordinatorRouteChildren,
)

interface DeptAdminRouteChildren {
  DeptAdminAttendanceRoute: typeof DeptAdminAttendanceRoute
  DeptAdminCertificatesRoute: typeof DeptAdminCertificatesRoute
  DeptAdminEventsRoute: typeof DeptAdminEventsRoute
  DeptAdminFacultyRoute: typeof DeptAdminFacultyRoute
  DeptAdminGalleryRoute: typeof DeptAdminGalleryRoute
  DeptAdminRegistrationsRoute: typeof DeptAdminRegistrationsRoute
  DeptAdminReportsRoute: typeof DeptAdminReportsRoute
  DeptAdminSettingsRoute: typeof DeptAdminSettingsRoute
  DeptAdminStudentsRoute: typeof DeptAdminStudentsRoute
  DeptAdminIndexRoute: typeof DeptAdminIndexRoute
}

const DeptAdminRouteChildren: DeptAdminRouteChildren = {
  DeptAdminAttendanceRoute: DeptAdminAttendanceRoute,
  DeptAdminCertificatesRoute: DeptAdminCertificatesRoute,
  DeptAdminEventsRoute: DeptAdminEventsRoute,
  DeptAdminFacultyRoute: DeptAdminFacultyRoute,
  DeptAdminGalleryRoute: DeptAdminGalleryRoute,
  DeptAdminRegistrationsRoute: DeptAdminRegistrationsRoute,
  DeptAdminReportsRoute: DeptAdminReportsRoute,
  DeptAdminSettingsRoute: DeptAdminSettingsRoute,
  DeptAdminStudentsRoute: DeptAdminStudentsRoute,
  DeptAdminIndexRoute: DeptAdminIndexRoute,
}

const DeptAdminRouteWithChildren = DeptAdminRoute._addFileChildren(
  DeptAdminRouteChildren,
)

interface StaffRouteChildren {
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffRegistrationsRoute: typeof StaffRegistrationsRoute
  StaffScanRoute: typeof StaffScanRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffRegistrationsRoute: StaffRegistrationsRoute,
  StaffScanRoute: StaffScanRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface EventsEventIdRouteChildren {
  EventsEventIdRegisterRoute: typeof EventsEventIdRegisterRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdRegisterRoute: EventsEventIdRegisterRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlumniRoute: AlumniRoute,
  CalendarRoute: CalendarRoute,
  CertificatesRoute: CertificatesRouteWithChildren,
  CoordinatorRoute: CoordinatorRouteWithChildren,
  DeptAdminRoute: DeptAdminRouteWithChildren,
  GalleryRoute: GalleryRoute,
  HelpRoute: HelpRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  QrPassRoute: QrPassRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRouteWithChildren,
  VotingRoute: VotingRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthDepartmentAdminRoute: AuthDepartmentAdminRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  LiveStreamIdRoute: LiveStreamIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
